apiVersion: v1
kind: Secret
metadata:
  name: devshop-secret
  namespace: devshop
type: Opaque
stringData:
  DB_PASSWORD: "devshop_dev_password"
  JWT_SECRET_KEY: "86e6541a0976633fcae5517b70341b1d6541c5ee585fcf6a31732614e579597"
  DATABASE_URL: "postgresql+psycopg://devshop:devshop_dev_password@devshop-postgres:5432/devshop"
