apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - devshop-config.yaml
  - devshop-serviceaccount.yaml
  - postgres-pvc.yaml
  - postgres.yaml
  - migration.yaml
  - devshop.yaml
  - devshop-secretproviderclass.yaml
  - devshop-serviceaccount.yaml