"""add product stock constraint

Revision ID: e1eaf7583baa
Revises: e2a8d032a083
Create Date: 2026-08-26 12:37:57.961704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1eaf7583baa'
down_revision: Union[str, Sequence[str], None] = 'e2a8d032a083'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint('ck_products_stock_quantity_non_negative', 'products', 'stock_quantity >= 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_products_stock_quantity_non_negative', 'products', type_='check')
    # ### end Alembic commands ###
