"""add unique constraint to cart items

Revision ID: e2a8d032a083
Revises: 3c33cdab53de
Create Date: 2026-08-25 15:50:51.598241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2a8d032a083'
down_revision: Union[str, Sequence[str], None] = '3c33cdab53de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_cart_item_cart_product', 'cart_items', ['cart_id', 'product_id'])
    op.drop_constraint(op.f('carts_user_id_key'), 'carts', type_='unique')
    op.create_unique_constraint('uq_carts_user_id', 'carts', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_carts_user_id', 'carts', type_='unique')
    op.create_unique_constraint(op.f('carts_user_id_key'), 'carts', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_cart_item_cart_product', 'cart_items', type_='unique')
    # ### end Alembic commands ###
