apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: devshop

resources:
  - ../../base
  - postgres-storageclass.yaml

patches:
  - target:
      version: v1
      kind: PersistentVolumeClaim
      name: devshop-postgres-data
      namespace: devshop
    path: postgres-pvc-patch.yaml
