apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: devshop-azuredisk
provisioner: disk.csi.azure.com
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Delete
parameters:
  skuName: StandardSSD_LRS
  fsType: ext4
