apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devshop
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/SJD16/DevShop.git
    targetRevision: master
    path: k8s/overlays/aws

  destination:
    server: https://kubernetes.default.svc
    namespace: devshop

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
