apiVersion: v1
kind: Pod
metadata:
  name: zap
  namespace: devshop
spec:
  containers:
    - name: zap
      image: zaproxy/zap-stable
      command:
        - sleep
        - "infinity"
      volumeMounts:
        - name: zap-work
          mountPath: /zap/wrk
  volumes:
    - name: zap-work
      emptyDir: {}
